### ISSUE TITLE
Fix type checking custom primitives

### ISSUE THREAD

**Issue by saulshanabrook** [egraphs-good/egglog#212]
It looks like in #176 there was a slight regression that breaks rules that use custom primitives that are not present in [the default `TypeInfo`](https://github.com/saulshanabrook/egg-smol/blob/47dba2bba6a426d0a554ce956eab238b2ff8d7bc/src/typechecking.rs#L35-L61).

This issue is blocking upgrading the Python bindings to recent commits (https://github.com/metadsl/egglog-python/pull/42) because we use a custom `PyObjectSort`.

The underlying problem introduced is that the desugaring pass checks (in `normalize_expr`) if a function is primitive by [creating a default `TypeInfo`](https://github.com/saulshanabrook/egg-smol/blob/47dba2bba6a426d0a554ce956eab238b2ff8d7bc/src/ast/desugar.rs#L128) and using that, instead of using the `TypeInfo` associated with the current graph:

I am not sure how to resolve this.

**Comment by oflatt** [comment]
That's a problem! Thanks for pointing it out.
The solution is that the desugaring pass needs access to the egraph's actual typeinfo, which is kind of annoying.
Two potential fixes:

1. put the type info in the desugar struct from the beginning, and everything refers to it instead of the "proof context"
2. pass the type info along all of the relevant methods in desugaring.

I think I prefer solution 1, unless anyone has a better solution
Anyways, totally reasonable if you don't feel like fixing this one @saulshanabrook

**Comment by saulshanabrook** [comment]
So you would up to make `TypeInfo` a member of the `Desugar` struct?

**Comment by oflatt** [comment]
Yep!
