### ISSUE TITLE
Why `function` which has `:merge` doesn't produce default value?

### ISSUE THREAD

**Issue by hatoo** [egraphs-good/egglog#253]
Because of this line 
https://github.com/egraphs-good/egglog/blob/3c89b7c48e10c30757f728af641aacacfe430256/src/typechecking.rs#L144

`function` which has `:merge` doesn't produce a default value. Which means
This code
```lisp
(sort S)
(function F (i64) S :merge new)

(F 0)
```
doesn't work but it looks good to me.
And if I remove `&& func.merge.is_none()`, all tests can be passed with a little change.

Could you tell me why `egglog` doesn't produce a default value if `:merge` is specified?

**Comment by oflatt** [comment]
Great question.
We are trying to clean up egglog's semantics and make a distinction between `datatype`s and other functions. Because you specified a merge function, we treat that table as different from a datatype, and only allow setting it using the `set` keyword.

This helps clarify the different between `set` and `union`, as well as preventing certain common bugs people write. We should write a better error message for this case though!

**Comment by hatoo** [comment]
Thank you for clarifying!

> and only allow setting it using the set keyword.

That makes sense. I feel I got more understanding for `egglog` 👍

**Comment by oflatt** [comment]
I think the documentation could also use some updating on this point! After we merge #249
