### ISSUE TITLE
Rust Usage Example?

### ISSUE THREAD

**Issue by jafioti** [egraphs-good/egglog#416]
I've been trying to figure out how to interface with egglog from rust as a native rust crate. I assume this should be possible without needing to write an egglog program as a string and run the whole parsing pipeline at once, but maybe it isn't?

For reference, I have a representation of expressions in my project:
```rust
pub enum Term {
    Num(i32),
    Var(char),
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Min,
    Max,
    And,
    Or,
    Gte,
    Lt,
}

pub struct Expression {
    pub terms:Vec<Term>,
}
```
which holds terms in reverse polish notation. I currently use egg for simplifications by converting the expressions to egg expressions, running eqsat, extracting, and converting back into my format. Is there a way to do this right now efficiently in egglog? Ideally I'd like to convert as directly as possible to the egglog representation, run eqsat, and convert back while minimizing intermediate translation layers.

I can't find any examples of egglog in rust, only in the language

**Comment by jafioti** [comment]
I see in integration_tests you have an example with parse_and_run_program. Is there a more rust-native way rather than requiring a re-parse each time? Or a way to save e-graph state incrementally to be re-used?

**Comment by saulshanabrook** [comment]
Yeah this has come up a few times, we should probably add some basic info on the README about this question.

See https://egraphs.zulipchat.com/#narrow/stream/375765-egg.2Fegglog/topic/Current.20state.20of.20egglog.20Rust.20API/near/421497895 for what I did with the Python API.

Basically I started out by going deep into the API and trying to expose lots of different methods. But then found that it made more sense for my use case to only expose basically:

1. Running commands
2. Getting extracted values and run information out
3. Serialized the e-graph
4. Extracting values based on ASTs

https://github.com/egraphs-good/egglog-python/blob/main/src/egraph.rs

So yeah, if you are going from Rust, I think I would either generate source or generate AST nodes (commands) and run those to do what you need. What's a bit counterintuitive is that at the moment it's maybe friendlier to actually build up the API from Python than it is from Rust, since no one has built a nice Rust wrapper around the commands yet that work with macros or anything.
